apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.env.secrets }}
  {{ tpl $key $ }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}